# Generated by Django 5.1.5 on 2025-02-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ustoz',
            options={'verbose_name_plural': 'Ustozlar'},
        ),
    ]
